---
- name: Configure Nginx to work over HTTPS
  hosts: windows
  tasks:
    - name: Ensure certificate directory exists
      win_file:
        path: C:\tools\nginx-1.27.0\conf\certs
        state: directory

    - name: Copy certificates to the Windows host
      win_copy:
        src: "{{ item }}"
        dest: C:\tools\nginx-1.27.0\conf\certs\{{ item }}
      with_items:
        - ca-cert.pem
        - server-cert.pem
        - server-key.pem

    - name: Copy Nginx configuration
      win_template:
        src: ../templates/nginx.conf.j2
        dest: C:\tools\nginx-1.27.0\conf\nginx.conf

    - name: Restart Nginx service
      win_service:
        name: nginx
        state: restarted
