---
- name: Install and configure Nginx on Windows
  hosts: windows
  tasks:
    - name: Install Nginx using Chocolatey
      win_chocolatey:
        name: nginx
        state: present

    - name: Copy custom nginx configuration
      ansible.builtin.copy:
        src: ../files/nginx.conf
        dest: C:\nginx\conf\nginx.conf
      notify: Restart Nginx Service

  handlers:
    - name: Restart Nginx Service
      ansible.windows.win_service:
        name: nginx
        state: restarted
