---
- name: Install and configure Nginx as a service
  hosts: windows
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Download Nginx
      win_get_url:
        url: http://nginx.org/download/nginx-1.18.0.zip
        dest: C:\nginx.zip

    - name: Unzip Nginx
      win_unzip:
        src: C:\nginx.zip
        dest: C:\nginx

    - name: Download WinSW
      win_get_url:
        url: https://github.com/winsw/winsw/releases/download/v2.12.0/WinSW-x64.exe
        dest: C:\nginx\nginx-service.exe

    - name: Create WinSW config for Nginx
      win_template:
        src: ../templates/nginx-service.xml.j2
        dest: C:\nginx\nginx-service.xml

    - name: Install Nginx service
      win_command: C:\nginx\nginx-service.exe install
      args:
        creates: C:\\nginx\\nginx-service.exe

    - name: Start Nginx service
      win_service:
        name: nginx
        path: C:\\nginx\\nginx-service.exe
        start_mode: auto
        state: started