---
- name: Install and configure Nginx on Windows
  hosts: windows
  vars_files:
    - ../vars/credentials.yml
  tasks:
    - name: Install Nginx using Chocolatey
      win_chocolatey:
        name: nginx
        package_params:
        - '/installLocation:C:\tools'
        state: present

  handlers:
    - name: Restart Nginx Service
      ansible.windows.win_service:
        name: nginx
        state: restarted
